#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"
self_dir="$(dirname "$(pwd -P)/$(basename ${BASH_SOURCE[0]})")"
cd - 1>/dev/null

preload() {
    . "${self_dir}/lib/ask.sh"

    . "${self_dir}/scripts/brew.sh"
    . "${self_dir}/scripts/mas.sh"
    . "${self_dir}/scripts/tweaks.sh"
    . "${self_dir}/scripts/apps.sh"
    . "${self_dir}/scripts/go.sh"
}

main() {
    preload

    if [[ -z "${1-}" ]] ; then
        echo "Profile name not specified. Run \"./bootstrap <profile_name>\" to specify."
        exit 1
    fi
    profile_name="$1"

    echo "Bootstrap started for profile \"${profile_name}\"."

    ask::construct true

    if ask::interactive "Check macOS Software Updates?"; then
        updates=$(softwareupdate -l -a 2>&1)
        echo -e "$updates"
        if [ -n "$updates" ] && ! echo "$updates" | grep -q "No new software available" && ask::interactive "Install Software Updates?"; then
            softwareupdate -i -a
        fi
    fi

    brew::install_homebrew
    brew::update
    brew::upgrade_core
    brew::upgrade_cask "${self_dir}/profiles/${profile_name}/brew_cask_pinned.list"

    brew::reconcile "${self_dir}/profiles/${profile_name}/brew.list"
    mas::reconcile "${self_dir}/profiles/${profile_name}/mas.list"

    tweaks::hostname ${profile_name}
    tweaks::switch_to_zsh
    tweaks::set_screenshots_dir

    # Make some dirs
    mkdir -p $HOME/go
    mkdir -p $HOME/Screenshots

    go::get_packages
    # temporary disabled.
    #apps::nodejs-n

    echo "Done bootstrapping!"
}

main "$@"
exit 0
