#!/bin/bash
set -euo pipefail

cd "$(dirname ${BASH_SOURCE[0]})"
self_dir="$(dirname "$(pwd -P)/$(basename ${BASH_SOURCE[0]})")"
cd - 1>/dev/null

preload() {
    . "${self_dir}/lib/ask.sh"

    . "${self_dir}/scripts/packages.sh"
    . "${self_dir}/scripts/mas.sh"
    . "${self_dir}/scripts/tweaks.sh"
    . "${self_dir}/scripts/apps.sh"
    . "${self_dir}/scripts/go.sh"
}

install_homebrew() {
    if ! which brew 1>/dev/null ; then
        echo "Install Homebrew..."
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    taps=(
        homebrew/cask
        homebrew/cask-versions
        homebrew/cask-fonts
    )
    taps_installed="$(HOMEBREW_NO_AUTO_UPDATE=1 brew tap)"
    for tap in "${taps[@]}"; do
        if ! echo "${taps_installed}" | grep -q "${tap}"; then
            echo "--> brew tap "${tap}""
            brew tap "${tap}"
        fi
    done
}

main() {
    preload

    if [[ -z "${1-}" ]] ; then
        echo "Profile name not specified. Run \"./bootstrap <profile_name>\" to specify."
        exit 1
    fi
    profile_name="$1"

    echo "Bootstrap started for profile \"${profile_name}\"."

    ask::construct true

    if ask::interactive "Check Software Updates (App Store)?"; then
        softwareupdate -i -a
    fi

    install_homebrew

    echo "--> brew update"
    brew update
    echo "--> brew outdated"
    outdated=$(brew outdated --verbose)
    echo -e "$outdated"
    if [ -n "$outdated" ] && ask::interactive "Run brew upgrade?"; then
        echo "--> brew upgrade --ignore-pinned"
        brew upgrade --ignore-pinned
        # echo "--> brew cleanup --prune=300"
        # brew cleanup --prune=300
    fi

    echo "--> brew cask outdated"
    outdated=$(brew cask outdated --verbose)
    echo -e "$outdated"
    if [ -n "$outdated" ] && ask::interactive "Run brew cask reinstall \$(brew cask outdated)?"; then
        echo "--> brew cask reinstall $(brew cask outdated)"
        brew cask outdated | xargs brew cask reinstall
        # brew cask cleanup
    fi

    packages::install "${self_dir}/profiles/${profile_name}/brew.list"
    mas::install_all "${self_dir}/profiles/${profile_name}/mas.list"

    tweaks::hostname ${profile_name}
    tweaks::switch_to_zsh
    tweaks::set_screenshots_dir

    # Make some dirs
    mkdir -p $HOME/go
    mkdir -p $HOME/Screenshots

    go::get_packages
    # temporary disabled.
    #apps::nodejs-n

    echo "Done bootstrapping!"
}

main "$@"
exit 0
